// packages/reactgarden/src/layouts/pages/charts/index.tsx
// @mui material components
import Grid from "@mui/material/Grid"

// ThreeD Garden components
import MDBox from "~/components/MDBox"
import MDTypography from "~/components/MDTypography"

// ThreeD Garden examples components
import DashboardLayout from "~/examples/LayoutContainers/DashboardLayout"
import DashboardNavbar from "~/examples/Navbars/DashboardNavbar"
import Footer from "~/examples/Footer"
import DefaultLineChart from "~/examples/Charts/LineCharts/DefaultLineChart"
import GradientLineChart from "~/examples/Charts/LineCharts/GradientLineChart"
import VerticalBarChart from "~/examples/Charts/BarCharts/VerticalBarChart"
import HorizontalBarChart from "~/examples/Charts/BarCharts/HorizontalBarChart"
import MixedChart from "~/examples/Charts/MixedChart"
import BubbleChart from "~/examples/Charts/BubbleChart"
import DefaultDoughnutChart from "~/examples/Charts/DoughnutCharts/DefaultDoughnutChart"
import PieChart from "~/examples/Charts/PieChart"
import RadarChart from "~/examples/Charts/RadarChart"
import PolarChart from "~/examples/Charts/PolarChart"

// Data
import defaultLineChartData from "~/layouts/pages/charts/data/defaultLineChartData"
import gradientLineChartData from "~/layouts/pages/charts/data/gradientLineChartData"
import verticalBarChartData from "~/layouts/pages/charts/data/verticalBarChartData"
import horizontalBarChartData from "~/layouts/pages/charts/data/horizontalBarChartData"
import mixedChartData from "~/layouts/pages/charts/data/mixedChartData"
import bubbleChartData from "~/layouts/pages/charts/data/bubbleChartData"
import defaultDoughnutChartData from "~/layouts/pages/charts/data/defaultDoughnutChartData"
import pieChartData from "~/layouts/pages/charts/data/pieChartData"
import radarChartData from "~/layouts/pages/charts/data/radarChartData"
import polarChartData from "~/layouts/pages/charts/data/polarChartData"

function Charts(): JSX.Element {
  return (
    <DashboardLayout>
      <DashboardNavbar />
      <MDBox my={3}>
        <MDBox mb={3}>
          <Grid container spacing={3}>
            <Grid item xs={12} md={6} sx={{ lineHeight: 0 }}>
              <MDTypography variant="h5">Charts</MDTypography>
              <MDTypography variant="button" color="text">
                Charts on this page use Chart.js - Simple yet flexible
                JavaScript charting for designers & developers.
              </MDTypography>
            </Grid>
          </Grid>
        </MDBox>
        <MDBox mb={6}>
          <Grid container spacing={3}>
            <Grid item xs={12} md={6}>
              <DefaultLineChart
                icon={{ component: "insights" }}
                title="Line chart"
                description="Product insights"
                chart={defaultLineChartData}
              />
            </Grid>
            <Grid item xs={12} md={6}>
              <GradientLineChart
                icon={{ component: "show_chart" }}
                title="Line chart with gradient"
                description="Visits from devices"
                chart={gradientLineChartData}
              />
            </Grid>
          </Grid>
        </MDBox>
        <MDBox mb={6}>
          <Grid container spacing={3}>
            <Grid item xs={12} md={6}>
              <VerticalBarChart
                icon={{ color: "dark", component: "leaderboard" }}
                title="Bar chart"
                description="Sales related to age average"
                chart={verticalBarChartData}
              />
            </Grid>
            <Grid item xs={12} md={6}>
              <HorizontalBarChart
                icon={{ color: "dark", component: "splitscreen" }}
                title="Bar chart horizontal"
                description="Sales related to age average"
                chart={horizontalBarChartData}
              />
            </Grid>
          </Grid>
        </MDBox>
        <MDBox mb={6}>
          <Grid container spacing={3}>
            <Grid item xs={12} md={6}>
              <MixedChart
                icon={{ color: "primary", component: "auto_graph" }}
                title="Mixed chart"
                description="Analytics Insights"
                height="19.75rem"
                chart={mixedChartData}
              />
            </Grid>
            <Grid item xs={12} md={6}>
              <BubbleChart
                icon={{ color: "primary", component: "multiline_chart" }}
                title="Bubble chart"
                description="Users divided by regions"
                chart={bubbleChartData}
              />
            </Grid>
          </Grid>
        </MDBox>
        <MDBox mb={6}>
          <Grid container spacing={3}>
            <Grid item xs={12} md={6}>
              <DefaultDoughnutChart
                icon={{ color: "success", component: "donut_small" }}
                title="Doughnut chart"
                description="Affiliates program"
                chart={defaultDoughnutChartData}
              />
            </Grid>
            <Grid item xs={12} md={6}>
              <PieChart
                icon={{ color: "success", component: "donut_small" }}
                title="Pie chart"
                description="Analytics Insights"
                chart={pieChartData}
              />
            </Grid>
          </Grid>
        </MDBox>
        <MDBox mb={3}>
          <Grid container spacing={3}>
            <Grid item xs={12} md={6}>
              <RadarChart
                icon={{ color: "warning", component: "data_saver_on" }}
                title="Radar chart"
                description="Sciences score"
                chart={radarChartData}
              />
            </Grid>
            <Grid item xs={12} md={6}>
              <PolarChart
                icon={{ color: "warning", component: "scatter_plot" }}
                title="Polar chart"
                description="Analytics Insights"
                chart={polarChartData}
              />
            </Grid>
          </Grid>
        </MDBox>
      </MDBox>
      <Footer />
    </DashboardLayout>
  )
}

export default Charts

// packages/nuxtgarden/pages/examples/Charts.vue
<template>
  <div class="py-4 container-fluid">
    <div class="row">
      <div class="col-md-6">
        <h5 class="mb-0">Charts</h5>
        <p class="mb-0 text-sm">
          Charts on this page use Chart.js - Simple yet flexible JavaScript
          charting for designers & developers.
        </p>
      </div>
    </div>
    <div class="mt-4 row">
      <div class="col-md-6">
        <div class="card z-index-2">
          <div class="p-3 pb-0 card-header">
            <h6>Line chart</h6>
          </div>
          <div class="p-3 card-body">
            <div class="chart">
              <line-chart />
            </div>
          </div>
        </div>
      </div>
      <div class="mt-4 col-md-6 mt-md-0">
        <div class="card z-index-2">
          <div class="p-3 pb-0 card-header">
            <h6>Line chart with gradient</h6>
          </div>
          <div class="p-3 card-body">
            <div class="chart">
              <line-chart-gradient />
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="mt-4 row">
      <div class="col-md-6">
        <div class="card z-index-2">
          <div class="p-3 pb-0 card-header">
            <h6>Bar chart</h6>
          </div>
          <div class="p-3 card-body">
            <div class="chart">
              <bar-chart />
            </div>
          </div>
        </div>
      </div>
      <div class="mt-4 col-md-6 mt-md-0">
        <div class="card z-index-2">
          <div class="p-3 pb-0 card-header">
            <h6>Bar chart horizontal</h6>
          </div>
          <div class="p-3 card-body">
            <div class="chart">
              <bar-chart-horizontal />
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="mt-4 row">
      <div class="col-md-6">
        <div class="card z-index-2">
          <div class="p-3 pb-0 card-header">
            <h6>Mixed chart</h6>
          </div>
          <div class="p-3 card-body">
            <div class="chart">
              <mixed-chart />
            </div>
          </div>
        </div>
      </div>
      <div class="mt-4 col-md-6 mt-md-0">
        <div class="card z-index-2">
          <div class="p-3 pb-0 card-header">
            <h6>Bubble chart</h6>
          </div>
          <div class="p-3 card-body">
            <div class="chart">
              <bubble-chart />
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="mt-4 row">
      <div class="col-md-6">
        <div class="card z-index-2">
          <div class="p-3 pb-0 card-header">
            <h6>Doughnut chart</h6>
          </div>
          <div class="p-3 card-body">
            <div class="chart">
              <doughnut-chart />
            </div>
          </div>
        </div>
      </div>
      <div class="mt-4 col-md-6 mt-md-0">
        <div class="card z-index-2">
          <div class="p-3 pb-0 card-header">
            <h6>Pie chart</h6>
          </div>
          <div class="p-3 card-body">
            <div class="chart">
              <pie-chart />
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="mt-4 row">
      <div class="col-md-6">
        <div class="card z-index-2">
          <div class="p-3 pb-0 card-header">
            <h6>Radar chart</h6>
          </div>
          <div class="p-5 card-body">
            <div class="chart">
              <radar-chart />
            </div>
          </div>
        </div>
      </div>
      <div class="mt-4 col-md-6 mt-md-0">
        <div class="card z-index-2">
          <div class="p-3 pb-0 card-header">
            <h6>Polar chart</h6>
          </div>
          <div class="p-5 card-body">
            <div class="chart">
              <polar-chart />
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import LineChart from "./components/LineChart.vue"
import LineChartGradient from "./components/LineChartGradient.vue"
import BarChart from "./components/BarChart.vue"
import BarChartHorizontal from "./components/BarChartHorizontal.vue"
import MixedChart from "./components/MixedChart.vue"
import BubbleChart from "./components/BubbleChart.vue"
import DoughnutChart from "./components/DoughnutChart.vue"
import PieChart from "./components/PieChart.vue"
import RadarChart from "./components/RadarChart.vue"
import PolarChart from "./components/PolarChart.vue"

export default {
  name: "Charts",
  components: {
    LineChart,
    LineChartGradient,
    BarChart,
    BarChartHorizontal,
    MixedChart,
    BubbleChart,
    DoughnutChart,
    PieChart,
    RadarChart,
    PolarChart,
  },
}
</script>
