// packages/vite-garden/src/views/auth/signup/Cover.vue
<template>
  <div class="container top-0 position-sticky z-index-sticky">
    <div class="row">
      <div class="col-12">
        <navbar
          isBlur="blur blur-rounded my-3 py-2 start-0 end-0 mx-4 shadow"
          btnBackground="bg-gradient-success"
          v-bind:darkMode="true"
        />
      </div>
    </div>
  </div>
  <main class="mt-0 main-content main-content-bg">
    <section>
      <div class="page-header min-vh-75">
        <div class="container">
          <div class="row">
            <div class="mx-auto col-xl-4 col-lg-5 col-md-6 d-flex flex-column">
              <div class="mt-5 card card-plain">
                <div class="card-header pb-0 text-left">
                  <h3 class="font-weight-bolder text-success text-gradient">
                    Join us today
                  </h3>
                  <p class="mb-0">Enter your email and password to register</p>
                </div>
                <div class="card-body pb-3">
                  <form role="form">
                    <label>Name</label>
                    <vsud-input
                      type="text"
                      placeholder="Name"
                      aria-label="Name"
                    />
                    <label>Email</label>
                    <vsud-input
                      type="email"
                      placeholder="Email"
                      aria-label="Email"
                    />
                    <label>Password</label>
                    <vsud-input
                      type="password"
                      placeholder="Password"
                      aria-label="Password"
                    />
                    <vsud-checkbox
                      id="flexCheckDefault"
                      class="font-weight-light"
                      checked
                    >
                      I agree the
                      <a
                        href="../../../pages/privacy.html"
                        class="text-dark font-weight-bolder"
                        >Terms and Conditions</a
                      >
                    </vsud-checkbox>
                    <div class="text-center">
                      <vsud-button
                        color="success"
                        variant="gradient"
                        fullWidth
                        class="mt-4 mb-0"
                        >Sign up</vsud-button
                      >
                    </div>
                  </form>
                </div>
                <div class="card-footer text-center pt-0 px-sm-4 px-1">
                  <p class="mb-4 mx-auto">
                    Already have an account?
                    <a
                      href="../../../pages/sign-in/sign-in-cover.html"
                      class="text-success text-gradient font-weight-bold"
                      >Sign in</a
                    >
                  </p>
                </div>
              </div>
            </div>
            <div class="col-md-6">
              <div
                class="top-0 oblique position-absolute h-100 d-md-block d-none me-n8"
              >
                <div
                  class="bg-cover oblique-image position-absolute fixed-top ms-auto h-100 z-index-0 ms-n6"
                  :style="{
                    backgroundImage:
                      'url(' +
                      require('@/assets/img/curved-images/curved11.jpg') +
                      ')',
                  }"
                ></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </main>
  <app-footer />
</template>

<script>
import Navbar from "@/examples/PageLayout/Navbar.vue";
import AppFooter from "@/examples/PageLayout/Footer.vue";
import VsudInput from "@/components/VsudInput.vue";
import VsudCheckbox from "@/components/VsudCheckbox.vue";
import VsudButton from "@/components/VsudButton.vue";
const body = document.getElementsByTagName("body")[0];

export default {
  name: "signin-cover",
  components: {
    Navbar,
    AppFooter,
    VsudInput,
    VsudCheckbox,
    VsudButton,
  },
  created() {
    this.$store.state.hideConfigButton = true;
    this.$store.state.showNavbar = false;
    this.$store.state.showSidenav = false;
    this.$store.state.showFooter = false;
    body.classList.remove("bg-gray-100");
  },
  beforeUnmount() {
    this.$store.state.hideConfigButton = false;
    this.$store.state.showNavbar = true;
    this.$store.state.showSidenav = true;
    this.$store.state.showFooter = true;
    body.classList.add("bg-gray-100");
  },
};
</script>

// pages/authentication/sign-up/cover/index.tsx
// nextjs components
import Link from 'next/link'

// @mui material components
import Card from '@mui/material/Card'
import Checkbox from '@mui/material/Checkbox'

// ThreeD Garden components
import MDBox from '#/lib/mui/MDBox'
import MDTypography from '#/lib/mui/MDTypography'
import MDInput from '#/lib/mui/MDInput'
import MDButton from '#/lib/mui/MDButton'

// Authentication layout components
import CoverLayout from '#/pages/authentication/components/CoverLayout'

// Images
import theImage from '#/lib/assets/images/any/bg-sign-up-cover.jpg'

function Cover(): JSX.Element {
  return (
    <CoverLayout image={theImage}>
      <Card>
        <MDBox
          variant='gradient'
          bgColor='info'
          borderRadius='lg'
          coloredShadow='success'
          mx={2}
          mt={-3}
          p={3}
          mb={1}
          textAlign='center'
        >
          <MDTypography
            variant='h4'
            fontWeight='medium'
            color='white'
            mt={1}
          >
            Join us today
          </MDTypography>
          <MDTypography
            display='block'
            variant='button'
            color='white'
            my={1}
          >
            Enter your email and password to register
          </MDTypography>
        </MDBox>
        <MDBox
          pt={4}
          pb={3}
          px={3}
        >
          <MDBox
            component='form'
            role='form'
          >
            <MDBox mb={2}>
              <MDInput
                type='text'
                label='Name'
                variant='standard'
                fullWidth
              />
            </MDBox>
            <MDBox mb={2}>
              <MDInput
                type='email'
                label='Email'
                variant='standard'
                fullWidth
              />
            </MDBox>
            <MDBox mb={2}>
              <MDInput
                type='password'
                label='Password'
                variant='standard'
                fullWidth
              />
            </MDBox>
            <MDBox
              display='flex'
              alignItems='center'
              ml={-1}
            >
              <Checkbox />
              <MDTypography
                variant='button'
                fontWeight='regular'
                color='text'
                sx={{ cursor: 'pointer', userSelect: 'none', ml: -1 }}
              >
                &nbsp;&nbsp;I agree the&nbsp;
              </MDTypography>
              <MDTypography
                component='a'
                href='#'
                variant='button'
                fontWeight='bold'
                color='info'
                textGradient
              >
                Terms and Conditions
              </MDTypography>
            </MDBox>
            <MDBox
              mt={4}
              mb={1}
            >
              <MDButton
                variant='gradient'
                color='info'
                fullWidth
              >
                sign in
              </MDButton>
            </MDBox>
            <MDBox
              mt={3}
              mb={1}
              textAlign='center'
            >
              <MDTypography
                variant='button'
                color='text'
              >
                Already have an account?{' '}
                <MDTypography
                  component={Link}
                  href='/authentication/sign-in/cover'
                  variant='button'
                  color='info'
                  fontWeight='medium'
                  textGradient
                >
                  Sign In
                </MDTypography>
              </MDTypography>
            </MDBox>
          </MDBox>
        </MDBox>
      </Card>
    </CoverLayout>
  )
}

export default Cover
